fix: Make header docs runnable + add support for empty header fields (#120)
**Before:**

```julia-repl
julia> img["KEY"] = nothing
ERROR: MethodError: no method matching FITSFiles.Card(::String, ::Nothing)
The type `FITSFiles.Card` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  FITSFiles.Card(::Any, ::Any, ::Any, ::Any, ::Any)
   @ FITSFiles ~/.julia/packages/FITSFiles/0MEHx/src/card.jl:232
  FITSFiles.Card(::S; ...) where S<:AbstractString
   @ FITSFiles ~/.julia/packages/FITSFiles/0MEHx/src/card.jl:237
  FITSFiles.Card(::S, ::V; ...) where {S<:AbstractString, V<:Union{Missing, AbstractString, Number}}
   @ FITSFiles ~/.julia/packages/FITSFiles/0MEHx/src/card.jl:237
  ...
```

**After:**

```julia-repl
julia> img["KEY"] = nothing
```